### ISSUE TITLE
c-sys-01-pending-reboot calls $machineName

### ISSUE THREAD

**Issue by Hurtrus** [My-Random-Thoughts/Server-QA-Checks#1]
**c-sys-01-pending-reboot** calls **$machineName** instead of **$serverName** 

$reg = [Microsoft.Win32.RegistryKey]::OpenRemoteBaseKey('LocalMachine', $machineName)

The results returned seem to reflect my local machine and not the remote machine.

Confirmed that replacing $machineName with $serverName returns the correct value from the remote server.

I am enjoying your work. Thank you for sharing

**Comment by My-Random-Thoughts** [comment]
Thanks, good spot, now fixed.
