### ISSUE TITLE
Great UI but why not Pester?

### ISSUE THREAD

**Issue by cparker4486** [My-Random-Thoughts/Server-QA-Checks#2]
Stumbled across this repo today. The UI looks awesome* but I see that you're not using Pester. What's your reasoning behind that? Just curious. Pester is meant for this kind of thing. You might be interested in https://github.com/PowerShell/Operation-Validation-Framework too. It's a tool for running ops-focused tests as opposed to regular Pester tests against scripts.

\* I'm loving that old-school BBS look. Those were the days...

**Comment by My-Random-Thoughts** [comment]
Thanks.  These were designed to be as simple as possible with zero requirements (apart from PowerShell v2).  It requires no installation of any third party tools or utilities.

I have seen OVF, but not used it.
