### ISSUE TITLE
Dealing with EPOCH time format/stamp

### ISSUE THREAD

**Issue by MartynKeigher** [My-Random-Thoughts/Server-QA-Checks#3]
Hey, 

Not so much an issue here, rather just a general question... 

I am working on my own compliance check for Webroot SecureAnywhere, to which I am using the McAfee check as a 'template'. Webroot stamps dates in the registry in EPOCH format (in the _UpdateTime_ key). How would one re-work this section to work with that format??

   ```
# Check DAT Update date
        Try
        {
            [datetime]$dtVal = '01/01/1901'
            $reg    = [Microsoft.Win32.RegistryKey]::OpenRemoteBaseKey('LocalMachine', $serverName)
            $regKey = $reg.OpenSubKey('Software\Wow6432Node\WRData\Status')
            If ($regKey) { $dtVal = $regKey.GetValue('UpdateTime') }
            Try {$regKey.Close() } Catch {}
            $reg.Close()
        }
```

![image](https://cloud.githubusercontent.com/assets/3298134/23835527/d7b93b1c-0736-11e7-9db4-c5d120136842.png)

Thanks in advance!! 
Martyn.

**Comment by My-Random-Thoughts** [comment]
A quick search for "PowerShell convert EPOCH" returns this quick two line code...

```
$origin = New-Object -Type DateTime -ArgumentList 1970, 1, 1, 0, 0, 0, 0
$whatIWant = $origin.AddSeconds($unixTime)
```

Give that a go, it should do what you need.  Once you have your script working, send it over and I'll include it if you like.
