### ISSUE TITLE
Fails to generate QA script when the ini file contains a space

### ISSUE THREAD

**Issue by ChrisWight** [My-Random-Thoughts/Server-QA-Checks#4]
Hey,

Have found that the configurator tools accepts a space in the Base Settings File field but then fails to generate the QA scripts even though it says it is successful. Once the space was removed the file generated as expected.

Can you screen the input for a space or automatically trim the spaces?

Cheers,
Chris

**Comment by My-Random-Thoughts** [comment]
Hey Chris,
Are you saying the filename contains a space and therefore it fails.?
Could you add a link to a screen shot please.?
Thanks

**Comment by ChrisWight** [comment]
http://imgur.com/a/zhIHU

The test qa script was generated using the SecurityAudit.ini after Security Audit.ini did not generate the QA script but there should have been a test2 qa generated.

**Comment by My-Random-Thoughts** [comment]
Great, thanks.  I have a look.

**Comment by My-Random-Thoughts** [comment]
All fixed.  Thanks for reporting it.

**Comment by ChrisWight** [comment]
Confirmed as working
