### ISSUE TITLE
Uncaught exceptions when running checks

### ISSUE THREAD

**Issue by ChrisWight** [My-Random-Thoughts/Server-QA-Checks#5]
Hey,

I believe it is this code from the License check which is throwing errors into the console when running the QA script.

    If ($check2.DiscoveredKeyManagementServiceMachineName -ne '') { $kms = $check2.DiscoveredKeyManagementServiceMachineName }
    If ($check2.KeyManagementServiceMachine               -ne '') { $kms = $check2.KeyManagementServiceMachine               }

Cheers,
Chris

**Comment by My-Random-Thoughts** [comment]
Do you have the error message you are getting.?  Or more details on what you are running the script on.
That code is working fine on everything I am running it on.

**Comment by ChrisWight** [comment]
Have updated the server names to match each box. 

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Scanning 2 servers
 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

server 2008r2 tmg server                                                                                                          (1/2)
   ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
   ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀Could not get objects from namespace ROOT\Cimv2. The RPC server is unavailable. (Exception from HRES
ULT: 0x800706BA)
    + CategoryInfo          : ObjectNotFound: (:) [Get-WmiObject], COMException
    + FullyQualifiedErrorId : INVALID_NAMESPACE_IDENTIFIER,Microsoft.PowerShell.Commands.GetWmiObjectCommand
    + PSComputerName        : localhost
Could not get objects from namespace ROOT\Cimv2. The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
    + CategoryInfo          : ObjectNotFound: (:) [Get-WmiObject], COMException
    + FullyQualifiedErrorId : INVALID_NAMESPACE_IDENTIFIER,Microsoft.PowerShell.Commands.GetWmiObjectCommand
    + PSComputerName        : localhost
▀
                                  5,  1,  9,  1,  2,  0

server 2008 sql server                                                                                                          (2/2)
   ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
   ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀Invalid query "SELECT KeyManagementServiceMachine, DiscoveredKeyManagementServiceMachineName FROM
SoftwareLicensingService"
    + CategoryInfo          : InvalidArgument: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand
    + PSComputerName        : localhost

▀
                                  4,  1, 10,  1,  2,  0

**Comment by My-Random-Thoughts** [comment]
Can you add -Verbose to the end of the QA command line please.  It will run each check one at a time to help correctly identify the failing check(s).

For the first error, it could be an issue with the server, 
If you can, download the WMI Explorer from https://wmie.codeplex.com/, and copy it to each of the servers.  Use it to see if that WMI key does exist and holds data.

**Comment by ChrisWight** [comment]
WMI is likely blocked being a TMG box but it shouldnt be throwing errors into the console?

Verbose output below

tmg
    c-sys-02-windows-license..................................................................................... : Coul
d not get objects from namespace ROOT\Cimv2. The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
    + CategoryInfo          : ObjectNotFound: (:) [Get-WmiObject], COMException
    + FullyQualifiedErrorId : INVALID_NAMESPACE_IDENTIFIER,Microsoft.PowerShell.Commands.GetWmiObjectCommand
    + PSComputerName        : localhost
Could not get objects from namespace ROOT\Cimv2. The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
    + CategoryInfo          : ObjectNotFound: (:) [Get-WmiObject], COMException
    + FullyQualifiedErrorId : INVALID_NAMESPACE_IDENTIFIER,Microsoft.PowerShell.Commands.GetWmiObjectCommand
    + PSComputerName        : localhost
■

      5,  1,  9,  1,  2,  0

  sql01                                                                                                          (2/2)
   Verbose information:
    c-sec-01-schannel-p1-ciphers................................................................................. : ■
    c-sec-02-schannel-p2-hashes.................................................................................. : ■
    c-sec-03-schannel-p3-keyexchangealgorithms................................................................... : ■
    c-sec-04-schannel-p4-protocols............................................................................... : ■
    c-sec-05-schannel-p5-cipher-order............................................................................ : ■
    c-sec-06-reject-enumerate-accounts........................................................................... : ■
    c-sec-07-reject-enumerate-shares............................................................................. : ■
    c-sec-08-domain-credential-caching........................................................................... : ■
    c-sec-09-request-admin-elevated.............................................................................. : ■
    c-sec-10-anonymous-pipe-share-access......................................................................... : ■
    c-sec-11-iis-default-page.................................................................................... : ■
    c-sec-12-smb-signing-on...................................................................................... : ■
    c-sec-13-rsa-authentication.................................................................................. : ■
    c-sec-14-firewall-rules...................................................................................... : ■
    c-sec-15-firewall-state...................................................................................... : ■
    c-sec-16-open-ports.......................................................................................... : ■
    c-sec-17-smb1-disabled....................................................................................... : ■
    c-sys-02-windows-license..................................................................................... : Inva
lid query "SELECT KeyManagementServiceMachine, DiscoveredKeyManagementServiceMachineName FROM
SoftwareLicensingService"
    + CategoryInfo          : InvalidArgument: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand
    + PSComputerName        : localhost

**Comment by ChrisWight** [comment]
I checked both our 2008 boxes with WMI Explorer and both are missing the DiscoveredKeyManagementServiceMachineName property

**Comment by My-Random-Thoughts** [comment]
I agree, it should not be spitting out errors.  I'll add some error checking to that check later today.
Thanks for reporting it.

**Comment by ChrisWight** [comment]
No worries, thanks for sharing this. Speaking of the TMG box not being able to connect, have you thought of having a connections section which tests different protocols with each check? Ping, WinRM, Dcom, WMI etc

**Comment by My-Random-Thoughts** [comment]
The engine does a PING and RPC port test (135), but that's it.

Version 4 of the checks, which I am working on now, will run with WinRM only for remote connections, so a lot of the issues I am seeing and working around will disappear.

**Comment by My-Random-Thoughts** [comment]
I have added some error handling to this check, can you see if this works for you please.

**Comment by ChrisWight** [comment]
Tested as working. Result now showing as an error
